"""Illustrative Taiwan-stock factor inputs for demo mode.

These numbers are placeholders for UI and pipeline development only.
They are not real-time market data and must not be treated as investment advice.
"""

from __future__ import annotations

DEMO_STOCK_FACTORS = {
    "2330": {
        "trend": 0.95,
        "volume": 0.80,
        "capital_flow": 0.88,
        "quality": 0.98,
        "momentum": 0.90,
        "sector": 0.94,
        "risk": 0.12,
        "relative_strength": 0.91,
        "risk_flags": ["Valuation premium"],
        "thesis": "Leader with strong trend quality and institutional sponsorship.",
    },
    "2454": {
        "trend": 0.90,
        "volume": 0.74,
        "capital_flow": 0.84,
        "quality": 0.93,
        "momentum": 0.87,
        "sector": 0.89,
        "risk": 0.16,
        "relative_strength": 0.88,
        "risk_flags": ["Earnings expectation sensitivity"],
        "thesis": "High-quality IC design leader with resilient momentum.",
    },
    "2303": {
        "trend": 0.84,
        "volume": 0.69,
        "capital_flow": 0.72,
        "quality": 0.80,
        "momentum": 0.74,
        "sector": 0.82,
        "risk": 0.18,
        "relative_strength": 0.76,
        "risk_flags": ["Cycle-sensitive pricing"],
        "thesis": "Constructive foundry trend with decent breadth support.",
    },
    "3711": {
        "trend": 0.83,
        "volume": 0.67,
        "capital_flow": 0.70,
        "quality": 0.82,
        "momentum": 0.73,
        "sector": 0.79,
        "risk": 0.22,
        "relative_strength": 0.75,
        "risk_flags": ["Need stronger follow-through"],
        "thesis": "Packaging and testing exposure with steady but not explosive setup.",
    },
    "3034": {
        "trend": 0.79,
        "volume": 0.61,
        "capital_flow": 0.64,
        "quality": 0.85,
        "momentum": 0.70,
        "sector": 0.78,
        "risk": 0.23,
        "relative_strength": 0.72,
        "risk_flags": ["Volume confirmation still moderate"],
        "thesis": "Healthy quality profile, but momentum needs firmer volume.",
    },
    "2317": {
        "trend": 0.88,
        "volume": 0.73,
        "capital_flow": 0.77,
        "quality": 0.82,
        "momentum": 0.79,
        "sector": 0.85,
        "risk": 0.19,
        "relative_strength": 0.81,
        "risk_flags": ["Large-cap rotation risk"],
        "thesis": "Broad AI supply-chain participation keeps the setup constructive.",
    },
    "2382": {
        "trend": 0.87,
        "volume": 0.76,
        "capital_flow": 0.79,
        "quality": 0.84,
        "momentum": 0.82,
        "sector": 0.88,
        "risk": 0.18,
        "relative_strength": 0.84,
        "risk_flags": ["Crowded AI theme"],
        "thesis": "AI server leadership and strong peer-relative strength.",
    },
    "3231": {
        "trend": 0.85,
        "volume": 0.79,
        "capital_flow": 0.81,
        "quality": 0.72,
        "momentum": 0.84,
        "sector": 0.86,
        "risk": 0.24,
        "relative_strength": 0.86,
        "risk_flags": ["Volatility above mega-cap peers"],
        "thesis": "Momentum leader with stronger volatility and execution risk.",
    },
    "6669": {
        "trend": 0.91,
        "volume": 0.71,
        "capital_flow": 0.82,
        "quality": 0.90,
        "momentum": 0.88,
        "sector": 0.90,
        "risk": 0.21,
        "relative_strength": 0.89,
        "risk_flags": ["High absolute price volatility"],
        "thesis": "Premium AI infrastructure name with high momentum quality.",
    },
    "3017": {
        "trend": 0.89,
        "volume": 0.72,
        "capital_flow": 0.78,
        "quality": 0.80,
        "momentum": 0.83,
        "sector": 0.84,
        "risk": 0.20,
        "relative_strength": 0.84,
        "risk_flags": ["Chasing risk after strong run"],
        "thesis": "Thermal theme remains strong, but entries need discipline.",
    },
    "3037": {
        "trend": 0.78,
        "volume": 0.64,
        "capital_flow": 0.60,
        "quality": 0.74,
        "momentum": 0.69,
        "sector": 0.76,
        "risk": 0.28,
        "relative_strength": 0.70,
        "risk_flags": ["PCB cycle still uneven"],
        "thesis": "Recovering PCB trend with only partial confirmation.",
    },
    "3189": {
        "trend": 0.74,
        "volume": 0.58,
        "capital_flow": 0.57,
        "quality": 0.71,
        "momentum": 0.66,
        "sector": 0.74,
        "risk": 0.32,
        "relative_strength": 0.65,
        "risk_flags": ["TPEX liquidity sensitivity"],
        "thesis": "OTC PCB beta with harsher liquidity penalty.",
    },
    "2356": {
        "trend": 0.76,
        "volume": 0.63,
        "capital_flow": 0.61,
        "quality": 0.70,
        "momentum": 0.68,
        "sector": 0.76,
        "risk": 0.27,
        "relative_strength": 0.69,
        "risk_flags": ["Needs stronger AI margin follow-through"],
        "thesis": "Reasonable AI linkage, but quality and flow are only moderate.",
    },
    "2376": {
        "trend": 0.82,
        "volume": 0.66,
        "capital_flow": 0.65,
        "quality": 0.75,
        "momentum": 0.73,
        "sector": 0.80,
        "risk": 0.26,
        "relative_strength": 0.74,
        "risk_flags": ["Theme rotation risk"],
        "thesis": "Solid AI exposure, but not the strongest flow profile in group.",
    },
    "2603": {
        "trend": 0.72,
        "volume": 0.70,
        "capital_flow": 0.59,
        "quality": 0.68,
        "momentum": 0.65,
        "sector": 0.63,
        "risk": 0.34,
        "relative_strength": 0.61,
        "risk_flags": ["Freight-rate volatility"],
        "thesis": "Shipping can move quickly, but regime support is less stable.",
    },
    "2615": {
        "trend": 0.68,
        "volume": 0.66,
        "capital_flow": 0.55,
        "quality": 0.62,
        "momentum": 0.60,
        "sector": 0.61,
        "risk": 0.38,
        "relative_strength": 0.58,
        "risk_flags": ["Higher beta within shipping"],
        "thesis": "Higher-risk shipping proxy with thinner quality support.",
    },
    "2882": {
        "trend": 0.75,
        "volume": 0.57,
        "capital_flow": 0.69,
        "quality": 0.82,
        "momentum": 0.63,
        "sector": 0.68,
        "risk": 0.18,
        "relative_strength": 0.62,
        "risk_flags": ["Rate-sensitive sentiment swings"],
        "thesis": "Financial defensiveness offsets slower momentum.",
    },
    "2881": {
        "trend": 0.77,
        "volume": 0.58,
        "capital_flow": 0.71,
        "quality": 0.84,
        "momentum": 0.65,
        "sector": 0.69,
        "risk": 0.18,
        "relative_strength": 0.64,
        "risk_flags": ["Dividend-cycle positioning risk"],
        "thesis": "Defensive financial setup with stable quality and flow.",
    },
    "2891": {
        "trend": 0.70,
        "volume": 0.54,
        "capital_flow": 0.62,
        "quality": 0.79,
        "momentum": 0.58,
        "sector": 0.66,
        "risk": 0.19,
        "relative_strength": 0.57,
        "risk_flags": ["Momentum lag vs peers"],
        "thesis": "Stable but slower financial name, better for defense than leadership.",
    },
    "1303": {
        "trend": 0.56,
        "volume": 0.45,
        "capital_flow": 0.42,
        "quality": 0.58,
        "momentum": 0.43,
        "sector": 0.44,
        "risk": 0.37,
        "relative_strength": 0.40,
        "risk_flags": ["Weak cyclical demand trend"],
        "thesis": "Still in a weaker materials regime and not a priority leader.",
    },
    "1216": {
        "trend": 0.64,
        "volume": 0.49,
        "capital_flow": 0.55,
        "quality": 0.76,
        "momentum": 0.48,
        "sector": 0.58,
        "risk": 0.18,
        "relative_strength": 0.46,
        "risk_flags": ["Defensive rotation only"],
        "thesis": "Consumer defensive profile, but low momentum limits ranking.",
    },
    "2207": {
        "trend": 0.69,
        "volume": 0.51,
        "capital_flow": 0.57,
        "quality": 0.81,
        "momentum": 0.56,
        "sector": 0.60,
        "risk": 0.19,
        "relative_strength": 0.54,
        "risk_flags": ["Demand-cycle sensitivity"],
        "thesis": "Quality consumer name with moderate trend support.",
    },
    "3661": {
        "trend": 0.93,
        "volume": 0.69,
        "capital_flow": 0.79,
        "quality": 0.91,
        "momentum": 0.92,
        "sector": 0.90,
        "risk": 0.26,
        "relative_strength": 0.93,
        "risk_flags": ["Very extended momentum"],
        "thesis": "Elite leadership profile, but extension risk must be respected.",
    },
    "5274": {
        "trend": 0.90,
        "volume": 0.64,
        "capital_flow": 0.75,
        "quality": 0.95,
        "momentum": 0.89,
        "sector": 0.88,
        "risk": 0.25,
        "relative_strength": 0.90,
        "risk_flags": ["Higher price volatility"],
        "thesis": "High-quality IC design leader with strong relative strength.",
    },
    "4938": {
        "trend": 0.61,
        "volume": 0.48,
        "capital_flow": 0.46,
        "quality": 0.62,
        "momentum": 0.44,
        "sector": 0.53,
        "risk": 0.31,
        "relative_strength": 0.42,
        "risk_flags": ["Lacks trend confirmation"],
        "thesis": "Electronics assembler without enough momentum leadership yet.",
    },
}
